version: "2"

run:
  go: "1.25"

linters:
  enable:
    - bodyclose
    - misspell
    - noctx
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
