// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pallasdb/v1/kv.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutMode int32

const (
	PutMode_PUT_MODE_UNSPECIFIED PutMode = 0
	PutMode_PUT_MODE_UPSERT      PutMode = 1
	PutMode_PUT_MODE_INSERT      PutMode = 2
	PutMode_PUT_MODE_UPDATE      PutMode = 3
)

// Enum value maps for PutMode.
var (
	PutMode_name = map[int32]string{
		0: "PUT_MODE_UNSPECIFIED",
		1: "PUT_MODE_UPSERT",
		2: "PUT_MODE_INSERT",
		3: "PUT_MODE_UPDATE",
	}
	PutMode_value = map[string]int32{
		"PUT_MODE_UNSPECIFIED": 0,
		"PUT_MODE_UPSERT":      1,
		"PUT_MODE_INSERT":      2,
		"PUT_MODE_UPDATE":      3,
	}
)

func (x PutMode) Enum() *PutMode {
	p := new(PutMode)
	*p = x
	return p
}

func (x PutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pallasdb_v1_kv_proto_enumTypes[0].Descriptor()
}

func (PutMode) Type() protoreflect.EnumType {
	return &file_pallasdb_v1_kv_proto_enumTypes[0]
}

func (x PutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutMode.Descriptor instead.
func (PutMode) EnumDescriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{0}
}

type ClusterMemberStatus int32

const (
	ClusterMemberStatus_CLUSTER_MEMBER_STATUS_UNSPECIFIED ClusterMemberStatus = 0
	ClusterMemberStatus_CLUSTER_MEMBER_STATUS_ALIVE       ClusterMemberStatus = 1
	ClusterMemberStatus_CLUSTER_MEMBER_STATUS_LEAVING     ClusterMemberStatus = 2
	ClusterMemberStatus_CLUSTER_MEMBER_STATUS_LEFT        ClusterMemberStatus = 3
	ClusterMemberStatus_CLUSTER_MEMBER_STATUS_FAILED      ClusterMemberStatus = 4
)

// Enum value maps for ClusterMemberStatus.
var (
	ClusterMemberStatus_name = map[int32]string{
		0: "CLUSTER_MEMBER_STATUS_UNSPECIFIED",
		1: "CLUSTER_MEMBER_STATUS_ALIVE",
		2: "CLUSTER_MEMBER_STATUS_LEAVING",
		3: "CLUSTER_MEMBER_STATUS_LEFT",
		4: "CLUSTER_MEMBER_STATUS_FAILED",
	}
	ClusterMemberStatus_value = map[string]int32{
		"CLUSTER_MEMBER_STATUS_UNSPECIFIED": 0,
		"CLUSTER_MEMBER_STATUS_ALIVE":       1,
		"CLUSTER_MEMBER_STATUS_LEAVING":     2,
		"CLUSTER_MEMBER_STATUS_LEFT":        3,
		"CLUSTER_MEMBER_STATUS_FAILED":      4,
	}
)

func (x ClusterMemberStatus) Enum() *ClusterMemberStatus {
	p := new(ClusterMemberStatus)
	*p = x
	return p
}

func (x ClusterMemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterMemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pallasdb_v1_kv_proto_enumTypes[1].Descriptor()
}

func (ClusterMemberStatus) Type() protoreflect.EnumType {
	return &file_pallasdb_v1_kv_proto_enumTypes[1]
}

func (x ClusterMemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterMemberStatus.Descriptor instead.
func (ClusterMemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Mode          PutMode                `protobuf:"varint,3,opt,name=mode,proto3,enum=pallasdb.v1.PutMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetMode() PutMode {
	if x != nil {
		return x.Mode
	}
	return PutMode_PUT_MODE_UNSPECIFIED
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Descending    bool                   `protobuf:"varint,3,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{6}
}

func (x *RangeRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RangeRequest) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *RangeRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type RangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{7}
}

func (x *RangeResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{9}
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{10}
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ClusterMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ClusterMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,3,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	SerfAddr      string                 `protobuf:"bytes,4,opt,name=serf_addr,json=serfAddr,proto3" json:"serf_addr,omitempty"`
	Status        ClusterMemberStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=pallasdb.v1.ClusterMemberStatus" json:"status,omitempty"`
	RaftVoter     bool                   `protobuf:"varint,6,opt,name=raft_voter,json=raftVoter,proto3" json:"raft_voter,omitempty"`
	Leader        bool                   `protobuf:"varint,7,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterMember) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *ClusterMember) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *ClusterMember) GetSerfAddr() string {
	if x != nil {
		return x.SerfAddr
	}
	return ""
}

func (x *ClusterMember) GetStatus() ClusterMemberStatus {
	if x != nil {
		return x.Status
	}
	return ClusterMemberStatus_CLUSTER_MEMBER_STATUS_UNSPECIFIED
}

func (x *ClusterMember) GetRaftVoter() bool {
	if x != nil {
		return x.RaftVoter
	}
	return false
}

func (x *ClusterMember) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

type GetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderRequest) Reset() {
	*x = GetLeaderRequest{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderRequest) ProtoMessage() {}

func (x *GetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{13}
}

type GetLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderResponse) Reset() {
	*x = GetLeaderResponse{}
	mi := &file_pallasdb_v1_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderResponse) ProtoMessage() {}

func (x *GetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pallasdb_v1_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_pallasdb_v1_kv_proto_rawDescGZIP(), []int{14}
}

func (x *GetLeaderResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetLeaderResponse) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

var File_pallasdb_v1_kv_proto protoreflect.FileDescriptor

const file_pallasdb_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x14pallasdb/v1/kv.proto\x12\vpallasdb.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"^\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.pallasdb.v1.PutModeR\x04mode\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"X\n" +
	"\fRangeRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x12\n" +
	"\x04stop\x18\x02 \x01(\fR\x04stop\x12\x1e\n" +
	"\n" +
	"descending\x18\x03 \x01(\bR\n" +
	"descending\"7\n" +
	"\rRangeResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"C\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\"\x0e\n" +
	"\fJoinResponse\"\x14\n" +
	"\x12ListMembersRequest\"K\n" +
	"\x13ListMembersResponse\x124\n" +
	"\amembers\x18\x01 \x03(\v2\x1a.pallasdb.v1.ClusterMemberR\amembers\"\xf0\x01\n" +
	"\rClusterMember\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\traft_addr\x18\x03 \x01(\tR\braftAddr\x12\x1b\n" +
	"\tserf_addr\x18\x04 \x01(\tR\bserfAddr\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .pallasdb.v1.ClusterMemberStatusR\x06status\x12\x1d\n" +
	"\n" +
	"raft_voter\x18\x06 \x01(\bR\traftVoter\x12\x16\n" +
	"\x06leader\x18\a \x01(\bR\x06leader\"\x12\n" +
	"\x10GetLeaderRequest\"I\n" +
	"\x11GetLeaderResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr*b\n" +
	"\aPutMode\x12\x18\n" +
	"\x14PUT_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPUT_MODE_UPSERT\x10\x01\x12\x13\n" +
	"\x0fPUT_MODE_INSERT\x10\x02\x12\x13\n" +
	"\x0fPUT_MODE_UPDATE\x10\x03*\xc2\x01\n" +
	"\x13ClusterMemberStatus\x12%\n" +
	"!CLUSTER_MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCLUSTER_MEMBER_STATUS_ALIVE\x10\x01\x12!\n" +
	"\x1dCLUSTER_MEMBER_STATUS_LEAVING\x10\x02\x12\x1e\n" +
	"\x1aCLUSTER_MEMBER_STATUS_LEFT\x10\x03\x12 \n" +
	"\x1cCLUSTER_MEMBER_STATUS_FAILED\x10\x042\x84\x02\n" +
	"\tKVService\x128\n" +
	"\x03Get\x12\x17.pallasdb.v1.GetRequest\x1a\x18.pallasdb.v1.GetResponse\x128\n" +
	"\x03Put\x12\x17.pallasdb.v1.PutRequest\x1a\x18.pallasdb.v1.PutResponse\x12A\n" +
	"\x06Delete\x12\x1a.pallasdb.v1.DeleteRequest\x1a\x1b.pallasdb.v1.DeleteResponse\x12@\n" +
	"\x05Range\x12\x19.pallasdb.v1.RangeRequest\x1a\x1a.pallasdb.v1.RangeResponse0\x012\xeb\x01\n" +
	"\x0eClusterService\x12;\n" +
	"\x04Join\x12\x18.pallasdb.v1.JoinRequest\x1a\x19.pallasdb.v1.JoinResponse\x12P\n" +
	"\vListMembers\x12\x1f.pallasdb.v1.ListMembersRequest\x1a .pallasdb.v1.ListMembersResponse\x12J\n" +
	"\tGetLeader\x12\x1d.pallasdb.v1.GetLeaderRequest\x1a\x1e.pallasdb.v1.GetLeaderResponseB,Z*github.com/teddymalhan/pallasdb/pb/v1;pbv1b\x06proto3"

var (
	file_pallasdb_v1_kv_proto_rawDescOnce sync.Once
	file_pallasdb_v1_kv_proto_rawDescData []byte
)

func file_pallasdb_v1_kv_proto_rawDescGZIP() []byte {
	file_pallasdb_v1_kv_proto_rawDescOnce.Do(func() {
		file_pallasdb_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pallasdb_v1_kv_proto_rawDesc), len(file_pallasdb_v1_kv_proto_rawDesc)))
	})
	return file_pallasdb_v1_kv_proto_rawDescData
}

var file_pallasdb_v1_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pallasdb_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pallasdb_v1_kv_proto_goTypes = []any{
	(PutMode)(0),                // 0: pallasdb.v1.PutMode
	(ClusterMemberStatus)(0),    // 1: pallasdb.v1.ClusterMemberStatus
	(*GetRequest)(nil),          // 2: pallasdb.v1.GetRequest
	(*GetResponse)(nil),         // 3: pallasdb.v1.GetResponse
	(*PutRequest)(nil),          // 4: pallasdb.v1.PutRequest
	(*PutResponse)(nil),         // 5: pallasdb.v1.PutResponse
	(*DeleteRequest)(nil),       // 6: pallasdb.v1.DeleteRequest
	(*DeleteResponse)(nil),      // 7: pallasdb.v1.DeleteResponse
	(*RangeRequest)(nil),        // 8: pallasdb.v1.RangeRequest
	(*RangeResponse)(nil),       // 9: pallasdb.v1.RangeResponse
	(*JoinRequest)(nil),         // 10: pallasdb.v1.JoinRequest
	(*JoinResponse)(nil),        // 11: pallasdb.v1.JoinResponse
	(*ListMembersRequest)(nil),  // 12: pallasdb.v1.ListMembersRequest
	(*ListMembersResponse)(nil), // 13: pallasdb.v1.ListMembersResponse
	(*ClusterMember)(nil),       // 14: pallasdb.v1.ClusterMember
	(*GetLeaderRequest)(nil),    // 15: pallasdb.v1.GetLeaderRequest
	(*GetLeaderResponse)(nil),   // 16: pallasdb.v1.GetLeaderResponse
}
var file_pallasdb_v1_kv_proto_depIdxs = []int32{
	0,  // 0: pallasdb.v1.PutRequest.mode:type_name -> pallasdb.v1.PutMode
	14, // 1: pallasdb.v1.ListMembersResponse.members:type_name -> pallasdb.v1.ClusterMember
	1,  // 2: pallasdb.v1.ClusterMember.status:type_name -> pallasdb.v1.ClusterMemberStatus
	2,  // 3: pallasdb.v1.KVService.Get:input_type -> pallasdb.v1.GetRequest
	4,  // 4: pallasdb.v1.KVService.Put:input_type -> pallasdb.v1.PutRequest
	6,  // 5: pallasdb.v1.KVService.Delete:input_type -> pallasdb.v1.DeleteRequest
	8,  // 6: pallasdb.v1.KVService.Range:input_type -> pallasdb.v1.RangeRequest
	10, // 7: pallasdb.v1.ClusterService.Join:input_type -> pallasdb.v1.JoinRequest
	12, // 8: pallasdb.v1.ClusterService.ListMembers:input_type -> pallasdb.v1.ListMembersRequest
	15, // 9: pallasdb.v1.ClusterService.GetLeader:input_type -> pallasdb.v1.GetLeaderRequest
	3,  // 10: pallasdb.v1.KVService.Get:output_type -> pallasdb.v1.GetResponse
	5,  // 11: pallasdb.v1.KVService.Put:output_type -> pallasdb.v1.PutResponse
	7,  // 12: pallasdb.v1.KVService.Delete:output_type -> pallasdb.v1.DeleteResponse
	9,  // 13: pallasdb.v1.KVService.Range:output_type -> pallasdb.v1.RangeResponse
	11, // 14: pallasdb.v1.ClusterService.Join:output_type -> pallasdb.v1.JoinResponse
	13, // 15: pallasdb.v1.ClusterService.ListMembers:output_type -> pallasdb.v1.ListMembersResponse
	16, // 16: pallasdb.v1.ClusterService.GetLeader:output_type -> pallasdb.v1.GetLeaderResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pallasdb_v1_kv_proto_init() }
func file_pallasdb_v1_kv_proto_init() {
	if File_pallasdb_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pallasdb_v1_kv_proto_rawDesc), len(file_pallasdb_v1_kv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pallasdb_v1_kv_proto_goTypes,
		DependencyIndexes: file_pallasdb_v1_kv_proto_depIdxs,
		EnumInfos:         file_pallasdb_v1_kv_proto_enumTypes,
		MessageInfos:      file_pallasdb_v1_kv_proto_msgTypes,
	}.Build()
	File_pallasdb_v1_kv_proto = out.File
	file_pallasdb_v1_kv_proto_goTypes = nil
	file_pallasdb_v1_kv_proto_depIdxs = nil
}
