// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gokv/v1/kv.proto

package gokvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutMode int32

const (
	PutMode_PUT_MODE_UNSPECIFIED PutMode = 0
	PutMode_PUT_MODE_UPSERT      PutMode = 1
	PutMode_PUT_MODE_INSERT      PutMode = 2
	PutMode_PUT_MODE_UPDATE      PutMode = 3
)

// Enum value maps for PutMode.
var (
	PutMode_name = map[int32]string{
		0: "PUT_MODE_UNSPECIFIED",
		1: "PUT_MODE_UPSERT",
		2: "PUT_MODE_INSERT",
		3: "PUT_MODE_UPDATE",
	}
	PutMode_value = map[string]int32{
		"PUT_MODE_UNSPECIFIED": 0,
		"PUT_MODE_UPSERT":      1,
		"PUT_MODE_INSERT":      2,
		"PUT_MODE_UPDATE":      3,
	}
)

func (x PutMode) Enum() *PutMode {
	p := new(PutMode)
	*p = x
	return p
}

func (x PutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gokv_v1_kv_proto_enumTypes[0].Descriptor()
}

func (PutMode) Type() protoreflect.EnumType {
	return &file_gokv_v1_kv_proto_enumTypes[0]
}

func (x PutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutMode.Descriptor instead.
func (PutMode) EnumDescriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_gokv_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_gokv_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Mode          PutMode                `protobuf:"varint,3,opt,name=mode,proto3,enum=gokv.v1.PutMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_gokv_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetMode() PutMode {
	if x != nil {
		return x.Mode
	}
	return PutMode_PUT_MODE_UNSPECIFIED
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_gokv_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_gokv_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_gokv_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Descending    bool                   `protobuf:"varint,3,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_gokv_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{6}
}

func (x *RangeRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RangeRequest) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *RangeRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type RangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_gokv_v1_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokv_v1_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_gokv_v1_kv_proto_rawDescGZIP(), []int{7}
}

func (x *RangeResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_gokv_v1_kv_proto protoreflect.FileDescriptor

const file_gokv_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x10gokv/v1/kv.proto\x12\agokv.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"Z\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12$\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x10.gokv.v1.PutModeR\x04mode\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"X\n" +
	"\fRangeRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x12\n" +
	"\x04stop\x18\x02 \x01(\fR\x04stop\x12\x1e\n" +
	"\n" +
	"descending\x18\x03 \x01(\bR\n" +
	"descending\"7\n" +
	"\rRangeResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value*b\n" +
	"\aPutMode\x12\x18\n" +
	"\x14PUT_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPUT_MODE_UPSERT\x10\x01\x12\x13\n" +
	"\x0fPUT_MODE_INSERT\x10\x02\x12\x13\n" +
	"\x0fPUT_MODE_UPDATE\x10\x032\xe4\x01\n" +
	"\tKVService\x120\n" +
	"\x03Get\x12\x13.gokv.v1.GetRequest\x1a\x14.gokv.v1.GetResponse\x120\n" +
	"\x03Put\x12\x13.gokv.v1.PutRequest\x1a\x14.gokv.v1.PutResponse\x129\n" +
	"\x06Delete\x12\x16.gokv.v1.DeleteRequest\x1a\x17.gokv.v1.DeleteResponse\x128\n" +
	"\x05Range\x12\x15.gokv.v1.RangeRequest\x1a\x16.gokv.v1.RangeResponse0\x01B.Z,github.com/teddymalhan/gokv/gokvpb/v1;gokvv1b\x06proto3"

var (
	file_gokv_v1_kv_proto_rawDescOnce sync.Once
	file_gokv_v1_kv_proto_rawDescData []byte
)

func file_gokv_v1_kv_proto_rawDescGZIP() []byte {
	file_gokv_v1_kv_proto_rawDescOnce.Do(func() {
		file_gokv_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gokv_v1_kv_proto_rawDesc), len(file_gokv_v1_kv_proto_rawDesc)))
	})
	return file_gokv_v1_kv_proto_rawDescData
}

var file_gokv_v1_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gokv_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gokv_v1_kv_proto_goTypes = []any{
	(PutMode)(0),           // 0: gokv.v1.PutMode
	(*GetRequest)(nil),     // 1: gokv.v1.GetRequest
	(*GetResponse)(nil),    // 2: gokv.v1.GetResponse
	(*PutRequest)(nil),     // 3: gokv.v1.PutRequest
	(*PutResponse)(nil),    // 4: gokv.v1.PutResponse
	(*DeleteRequest)(nil),  // 5: gokv.v1.DeleteRequest
	(*DeleteResponse)(nil), // 6: gokv.v1.DeleteResponse
	(*RangeRequest)(nil),   // 7: gokv.v1.RangeRequest
	(*RangeResponse)(nil),  // 8: gokv.v1.RangeResponse
}
var file_gokv_v1_kv_proto_depIdxs = []int32{
	0, // 0: gokv.v1.PutRequest.mode:type_name -> gokv.v1.PutMode
	1, // 1: gokv.v1.KVService.Get:input_type -> gokv.v1.GetRequest
	3, // 2: gokv.v1.KVService.Put:input_type -> gokv.v1.PutRequest
	5, // 3: gokv.v1.KVService.Delete:input_type -> gokv.v1.DeleteRequest
	7, // 4: gokv.v1.KVService.Range:input_type -> gokv.v1.RangeRequest
	2, // 5: gokv.v1.KVService.Get:output_type -> gokv.v1.GetResponse
	4, // 6: gokv.v1.KVService.Put:output_type -> gokv.v1.PutResponse
	6, // 7: gokv.v1.KVService.Delete:output_type -> gokv.v1.DeleteResponse
	8, // 8: gokv.v1.KVService.Range:output_type -> gokv.v1.RangeResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gokv_v1_kv_proto_init() }
func file_gokv_v1_kv_proto_init() {
	if File_gokv_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gokv_v1_kv_proto_rawDesc), len(file_gokv_v1_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gokv_v1_kv_proto_goTypes,
		DependencyIndexes: file_gokv_v1_kv_proto_depIdxs,
		EnumInfos:         file_gokv_v1_kv_proto_enumTypes,
		MessageInfos:      file_gokv_v1_kv_proto_msgTypes,
	}.Build()
	File_gokv_v1_kv_proto = out.File
	file_gokv_v1_kv_proto_goTypes = nil
	file_gokv_v1_kv_proto_depIdxs = nil
}
